name: tests

on: [push]

env:
  USE_CYTHONIZE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Cython numpy
        pip install .
    - name: run pytest
      run: |
        pip install pytest
        pytest
